### ISSUE TITLE
Get-GitFlowStatus error during hot-fix listing

### ISSUE THREAD

**Issue by dermeister0** [Saritasa/PSGallery#58]
```
PS C:\Work\example> Get-GitFlowStatus -BranchType Hotfix
Get-GitFlowStatus : Sequence contains no elements
At line:1 char:1
+ Get-GitFlowStatus -BranchType Hotfix
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-GitFlowStatus], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Saritasa.Git.GitFlowStatus.GetGitFlowStatusCmdlet
```

**Comment by dermeister0** [comment]
```
Error: 7/6/2017 7:13:31 PM:
 +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ [<<==>>] Exception: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. --> Unable to load DLL 'git2-15e1193': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
```

**Comment by dermeister0** [comment]
```
2017-07-06 19:30:13.4328|ERROR|Saritasa.Git.GitFlowStatus.GetGitFlowStatusCmdlet|System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Saritasa.Git.GitFlowStatus.GetGitFlowStatusCmdlet.GetMostFrequentContributor(ICommitLog commits) in C:\Work\PSGallery\src\Saritasa.Git\GetGitFlowStatusCmdlet.cs:line 188
   at Saritasa.Git.GitFlowStatus.GetGitFlowStatusCmdlet.ProcessBranch(Branch branch) in C:\Work\PSGallery\src\Saritasa.Git\GetGitFlowStatusCmdlet.cs:line 173
   at Saritasa.Git.GitFlowStatus.GetGitFlowStatusCmdlet.ProcessRecord() in C:\Work\PSGallery\src\Saritasa.Git\GetGitFlowStatusCmdlet.cs:line 113
```

```
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Saritasa.Git.GitFlowStatus.GetGitFlowStatusCmdlet.GetMostFrequentContributor(ICommitLog commits) in C:\Work\PSGallery\src\Saritasa.Git\GetGitFlowStatusCmdlet.cs:line 198
   at Saritasa.Git.GitFlowStatus.GetGitFlowStatusCmdlet.ProcessBranch(Branch branch) in C:\Work\PSGallery\src\Saritasa.Git\GetGitFlowStatusCmdlet.cs:line 180
   at Saritasa.Git.GitFlowStatus.GetGitFlowStatusCmdlet.ProcessRecord() in C:\Work\PSGallery\src\Saritasa.Git\GetGitFlowStatusCmdlet.cs:line 115
```
