### ISSUE TITLE
yo psgallery fails

### ISSUE THREAD

**Issue by ko-vasilev** [Saritasa/PSGallery#97]
When running `yo psgallery`, I get the following error:
```
module.exports = generators.Base.extend({
                                 ^
TypeError: Cannot read property 'extend' of undefined
    at Object.<anonymous> (C:\Users\Konstantin Vasilev\AppData\Roaming\npm\node_modules\generator-psgallery\app\index.js:15:34)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.get [as psgallery:app] (C:\Users\Konstantin Vasilev\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\store.js:39:27)
    at Store.get (C:\Users\Konstantin Vasilev\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\store.js:62:39)
```

Windows 10 Pro x64
Yeoman version: 2.0.5
generator-psgallery version: 1.9.0
Nodejs version: 8.9.4
Npm version: 5.6.0

**Comment by dermeister0** [comment]
Fixed in version 1.9.1.
